/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author asus
 */
public class panelTrCust extends javax.swing.JPanel {
    private ArrayList<Barang> keranjangBelanja;
    /**
     * Creates new form panelPelanggan
     */
    public panelTrCust() {
        initComponents();
        keranjangBelanja = new ArrayList<>();
    }
    
   private void showData(java.util.Date tanggalAwal, java.util.Date tanggalAkhir) {
    DefaultTableModel model = (DefaultTableModel) tblSupp.getModel();
    model.setRowCount(0);

    // Query SQL menggunakan '?' sebagai placeholder untuk tanggal
    String sql = "SELECT " +
                 "t.tanggal_transaksi, t.ID_Transaksi, p.username AS Nama_Pelanggan, b.Nama_Barang, " +
                 "dp.Jumlah, dp.Harga_Saat_Transaksi, (dp.Jumlah * dp.Harga_Saat_Transaksi) AS Subtotal " +
                 "FROM data.detail_penjualan dp " +
                 "JOIN data.transaksi_penjualan t ON dp.ID_Transaksi = t.ID_Transaksi " +
                 "JOIN data.konsumen p ON t.ID_Pelanggan = p.id " +
                 "JOIN data.barang b ON dp.ID_Barang = b.ID_Barang " +
                 "WHERE DATE(t.tanggal_transaksi) BETWEEN ? AND ? " + // Gunakan placeholder
                 "ORDER BY t.tanggal_transaksi, t.ID_Transaksi";

    try (Connection conn = koneksi.getKoneksi();
         PreparedStatement pstmt = conn.prepareStatement(sql)) { // Gunakan PreparedStatement

        // Konversi java.util.Date ke java.sql.Date
        java.sql.Date sqlTanggalAwal = new java.sql.Date(tanggalAwal.getTime());
        java.sql.Date sqlTanggalAkhir = new java.sql.Date(tanggalAkhir.getTime());
        
        // Set nilai placeholder '?' dengan tanggal yang dipilih
        pstmt.setDate(1, sqlTanggalAwal);
        pstmt.setDate(2, sqlTanggalAkhir);
        
        try (ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                java.sql.Timestamp timestamp = rs.getTimestamp("tanggal_transaksi");
                String tanggalFormatted = new java.text.SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(timestamp);

                model.addRow(new Object[]{
                    tanggalFormatted,
                    rs.getInt("ID_Transaksi"),
                    rs.getString("Nama_Pelanggan"),
                    rs.getString("Nama_Barang"),
                    rs.getInt("Jumlah"),
                    rs.getInt("Harga_Saat_Transaksi"),
                    rs.getInt("Subtotal")
                });
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        e.printStackTrace();
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupp = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        jdcTanggalAwal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jdcTanggalAkhir = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnTampil = new javax.swing.JButton();

        setOpaque(false);

        tblSupp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal Transaksi", "ID Supplier", "Nama Pelanggan", "Nama Barang", "Jumlah", "Harga Satuan", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSupp.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblSupp);
        tblSupp.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jdcTanggalAwal.setDateFormatString("d MMM, yyyy");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Tanggal Awal");

        jdcTanggalAkhir.setDateFormatString("d MMM, yyyy");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Tanggal Akhir");

        btnTampil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTampil.setText("TAMPIL DATA");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdcTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdcTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTampil)
                        .addGap(34, 34, 34)))
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrint)
                        .addComponent(btnTampil))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdcTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // Di dalam event 'actionPerformed' untuk tombol 'PRINT'
        java.util.Date tanggalAwal = jdcTanggalAwal.getDate();
        java.util.Date tanggalAkhir = jdcTanggalAkhir.getDate();

        if (tanggalAwal == null || tanggalAkhir == null) {
            JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal dan tampilkan datanya terlebih dahulu.", "Input Tidak Lengkap", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String namaFile = "src/Report/reportCust.jasper"; // Pastikan path benar
            Connection conn = koneksi.getKoneksi();
    
            HashMap<String, Object> parameter = new HashMap<>();
            parameter.put("TANGGAL_AWAL", tanggalAwal);
            parameter.put("TANGGAL_AKHIR", tanggalAkhir);

            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
    
            JasperViewer.viewReport(jasperPrint, false);
    
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan laporan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        // Di dalam event 'actionPerformed' untuk tombol 'btnTampilkan'
        java.util.Date tglAwal = jdcTanggalAwal.getDate();
        java.util.Date tglAkhir = jdcTanggalAkhir.getDate();

        // Validasi input
        if (tglAwal == null || tglAkhir == null) {
            JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal terlebih dahulu.", "Input Tidak Lengkap", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tglAwal.after(tglAkhir)) {
            JOptionPane.showMessageDialog(this, "Tanggal Awal tidak boleh setelah Tanggal Akhir.", "Input Salah", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Panggil method showData dengan tanggal yang dipilih
        showData(tglAwal, tglAkhir);
    }//GEN-LAST:event_btnTampilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnTampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdcTanggalAkhir;
    private com.toedter.calendar.JDateChooser jdcTanggalAwal;
    private javax.swing.JTable tblSupp;
    // End of variables declaration//GEN-END:variables
}
