/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.awt.*;
import java.awt.event.*;
import javax.swing.table.*;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import java.io.File;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author msiti
 */
public class reportSupp extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelFormSupp
     */
    public reportSupp() {
        initComponents();
        showData();
    }

    private void cariData() {
    DefaultTableModel model = (DefaultTableModel) tblSupp.getModel();
    model.setRowCount(0);
    

    String sql = ("SELECT * from data.supplier WHERE " + cmbIdSupplier.getSelectedItem().toString() + " LIKE '%" + txtSearch.getText() + "%'");

        try (Connection conn = koneksi.getKoneksi(); // Menggunakan koneksi dari class koneksi.java
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_Supplier"),
                    rs.getString("Nama_Perusahaan"),
                    rs.getString("Kontak_PIC"),
                    rs.getString("No_Telepon"),
                    rs.getString("Email"),
                    rs.getString("Alamat"),
                });
            }
        } catch (Exception ex) {
        ex.printStackTrace(); // Debugging
        JOptionPane.showMessageDialog(null, "Gagal mengambil data:\n" + ex.getMessage());
        }
}
    
    private void showData() {
        DefaultTableModel model = (DefaultTableModel) tblSupp.getModel();
        model.setRowCount(0);

        String sql = "SELECT B.ID_Barang, B.Nama_Barang, B.ID_Supplier, S.Nama_Perusahaan, S.Kontak_PIC, S.No_Telepon, S.Email, S.Alamat " +
                     "FROM data.Barang B JOIN data.Supplier S ON B.ID_Supplier = S.ID_Supplier";
        
        try (Connection conn = koneksi.getKoneksi(); // PANGGIL METODE KONEKSI ANDA DI SINI
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_Supplier"),
                    rs.getString("Nama_Perusahaan"),
                    rs.getString("Kontak_PIC"),
                    rs.getString("No_Telepon"),
                    rs.getString("Email"),
                    rs.getString("Alamat"),
                    rs.getString("ID_Barang"),
                    rs.getString("Nama_Barang")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error memuat data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void kosong() {
        txtSearch.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblSupp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmbIdSupplier = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1282, 721));

        jScrollPane3.setBackground(new java.awt.Color(152, 124, 12));

        tblSupp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblSupp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Supplier", "Nama Perusaan", "Kontak Personal", "No. Telepon", "Email", "Alamat", "ID Barang", "Nama Barang"
            }
        ));
        jScrollPane3.setViewportView(tblSupp);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cari Data");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        cmbIdSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID_Supplier", "Nama_Perusahaan", "Kontak_PIC", "No_Telepon", "Email" }));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("CARI");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(cmbIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnClear)
                    .addComponent(btnPrint))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(126, 126, 126))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        kosong();
        showData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        btnSearch.doClick();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
      try {
        String namaFile = "src/Report/report1.jasper";
        Connection conn = koneksi.getKoneksi();
        Map<String,Object> parameters = new HashMap<>();
        // tambahkan parameter jika perlu, misal:
        // parameters.put("PARAM_TGL", new java.util.Date());

        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(new File(namaFile));
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);

        // Buat viewer sebagai Swing component
        JRViewer viewer = new JRViewer(jasperPrint);

        // Bungkus di dalam JFrame baru, atau tambahkan ke panel di form utama
        JFrame reportFrame = new JFrame("Preview Laporan");
        reportFrame.getContentPane().add(viewer);
        reportFrame.setSize(800, 600);
        reportFrame.setLocationRelativeTo(null);
        reportFrame.setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Gagal memuat report:\n" + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbIdSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblSupp;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
